"""add_candidate_notes_to_interviews

Revision ID: 0003_add_candidate_notes_to_interviews
Revises: de5fe36ab57c
Create Date: 2026-08-21 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003_add_candidate_notes'
down_revision: Union[str, None] = 'de5fe36ab57c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('candidate_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'candidate_notes')
    # ### end Alembic commands ###