"""create_password_reset_otp_table

Revision ID: 0005_otp
Revises: 0004_create_notifications_table
Create Date: 2026-08-22 15:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0005_otp'
down_revision: Union[str, None] = '0004_create_notifications_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_otps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('reset_token_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False, server_default=sa.text('0')),
    sa.Column('max_attempts', sa.Integer(), nullable=False, server_default=sa.text('5')),
    sa.Column('is_used', sa.Boolean(), nullable=False, server_default=sa.text('0')),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_otps_email_is_used_expires_at', 'password_reset_otps', ['email', 'is_used', 'expires_at'], unique=False)
    # Add last_password_reset column to users table
    op.add_column('users', sa.Column('last_password_reset', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_password_reset')
    op.drop_index('ix_password_reset_otps_email_is_used_expires_at', table_name='password_reset_otps')
    op.drop_table('password_reset_otps')
    # ### end Alembic commands ###