"""create_recruitment_subscription_payment_tables

Revision ID: 47c75548f388
Revises: remove_candidate_skill
Create Date: 2026-10-01 18:19:49.344044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c75548f388'
down_revision: Union[str, None] = 'remove_candidate_skill'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruitment_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255).with_variant(sa.NVARCHAR(255), 'mssql'), nullable=False),
    sa.Column('description', sa.Text().with_variant(sa.NVARCHAR(), 'mssql'), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('max_job_posts', sa.Integer(), nullable=False),
    sa.Column('max_candidate_searches', sa.Integer(), nullable=True),
    sa.Column('max_ai_features', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recruitment_plans_display_order', 'recruitment_plans', ['display_order'], unique=False)
    op.create_index('ix_recruitment_plans_is_active', 'recruitment_plans', ['is_active'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['recruitment_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('payment_orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('internal_order_id', sa.String(length=100), nullable=False),
    sa.Column('provider_order_id', sa.String(length=100), nullable=True),
    sa.Column('provider_request_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['recruitment_plans.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('internal_order_id'),
    )
    # Filtered unique indexes for SQL Server nullable provider identifiers
    # Allows multiple NULLs, enforces uniqueness for non-NULL values
    op.create_index(
        'ix_payment_orders_provider_order_id_unique',
        'payment_orders',
        ['provider_order_id'],
        unique=True,
        mssql_where=sa.text('provider_order_id IS NOT NULL'),
    )
    op.create_index(
        'ix_payment_orders_provider_request_id_unique',
        'payment_orders',
        ['provider_request_id'],
        unique=True,
        mssql_where=sa.text('provider_request_id IS NOT NULL'),
    )

    op.create_table('payment_transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_order_id', sa.Uuid(), nullable=False),
    sa.Column('provider_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('provider_result_code', sa.String(length=50), nullable=True),
    sa.Column('provider_message', sa.String(length=500), nullable=True),
    sa.Column('provider_response_metadata', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['payment_order_id'], ['payment_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    # Filtered unique index for SQL Server nullable provider_transaction_id
    op.create_index(
        'ix_payment_transactions_provider_transaction_id_unique',
        'payment_transactions',
        ['provider_transaction_id'],
        unique=True,
        mssql_where=sa.text('provider_transaction_id IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payment_transactions_provider_transaction_id_unique', table_name='payment_transactions')
    op.drop_index('ix_payment_orders_provider_request_id_unique', table_name='payment_orders')
    op.drop_index('ix_payment_orders_provider_order_id_unique', table_name='payment_orders')
    op.drop_table('payment_transactions')
    op.drop_table('payment_orders')
    op.drop_table('subscriptions')
    op.drop_index('ix_recruitment_plans_is_active', table_name='recruitment_plans')
    op.drop_index('ix_recruitment_plans_display_order', table_name='recruitment_plans')
    op.drop_table('recruitment_plans')
    # ### end Alembic commands ###