"""add lock_reason locked_at locked_by to users

Revision ID: 7c3a8d3084d3
Revises: 0005_otp
Create Date: 2026-08-27 14:20:31.130564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '7c3a8d3084d3'
down_revision: Union[str, None] = '0005_otp'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id_is_read_created_at'), table_name='notifications')
    op.add_column('users', sa.Column('lock_reason', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('locked_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('locked_by', sa.Uuid(), nullable=True))
    op.alter_column('users', 'last_password_reset',
               existing_type=mssql.DATETIMEOFFSET(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_foreign_key(None, 'users', 'users', ['locked_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'last_password_reset',
               existing_type=sa.DateTime(),
               type_=mssql.DATETIMEOFFSET(),
               existing_nullable=True)
    op.drop_column('users', 'locked_by')
    op.drop_column('users', 'locked_at')
    op.drop_column('users', 'lock_reason')
    op.create_index(op.f('ix_notifications_user_id_is_read_created_at'), 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    # ### end Alembic commands ###
