"""Integration test for interview scheduling flush behavior."""

import uuid
from datetime import datetime, timedelta, timezone

import pytest
from httpx import AsyncClient

from app.core.config import settings
from app.database.session import async_session_factory
from app.models import Interview, Application, Job, User, Company, CandidateProfile, RecruiterProfile
from app.models import Notification
from app.domain.enums import InterviewStatus, InterviewType, ApplicationStatus, UserRole, CompanySize
from tests.integration.api.conftest import API_V1, PASSWORD


@pytest.mark.asyncio
class TestInterviewScheduleFlush:
    """Integration test for interview scheduling flush behavior."""

    async def test_interview_id_generated_after_flush(self):
        """Test that interview.id is generated after session.flush()."""
        from app.database.session import async_session_factory
        from app.models import Interview, Application, Job, User, Company, CandidateProfile, RecruiterProfile
        from app.domain.enums import InterviewStatus, InterviewType, ApplicationStatus, UserRole, CompanySize
        import uuid
        from datetime import datetime, timedelta, timezone
        
        async with async_session_factory() as session:
            # Create test data
            company = Company(
                id=uuid.uuid4(),
                name="Test Company",
                slug="test-company",
                tax_code="123456789",
                size=CompanySize.STARTUP
            )
            session.add(company)
            
            user = User(
                id=uuid.uuid4(),
                email="test@example.com",
                password_hash="hash",
                role="recruiter",
                is_active=True
            )
            session.add(user)
            
            recruiter_profile = RecruiterProfile(
                id=uuid.uuid4(),
                user_id=user.id,
                company_id=company.id,
                full_name="Test Recruiter"
            )
            session.add(recruiter_profile)
            
            job = Job(
                id=uuid.uuid4(),
                company_id=company.id,
                title="Test Job",
                description="Test job",
                status="published",
                job_type="full_time",
                workplace_type="remote",
                location="Remote"
            )
            session.add(job)
            
            candidate_user = User(
                id=uuid.uuid4(),
                email="candidate@example.com",
                password_hash="hash",
                role="candidate",
                is_active=True
            )
            session.add(candidate_user)
            
            candidate_profile = CandidateProfile(
                id=uuid.uuid4(),
                user_id=candidate_user.id,
                full_name="Test Candidate"
            )
            session.add(candidate_profile)
            
            application = Application(
                id=uuid.uuid4(),
                candidate_id=candidate_profile.id,
                job_id=job.id,
                status=ApplicationStatus.APPLIED
            )
            session.add(application)
            
            await session.flush()
            
            # Create interview
            interview = Interview(
                application_id=application.id,
                scheduled_at=datetime.now(timezone.utc) + timedelta(days=1),
                duration_minutes=60,
                interview_type=InterviewType.TECHNICAL,
                meeting_url="https://meet.example.com",
                location="Office",
                notes="Test interview",
                status=InterviewStatus.SCHEDULED
            )
            
            # Before flush, id should be None
            assert interview.id is None
            
            session.add(interview)
            await session.flush()
            
            # After flush, id should be generated
            assert interview.id is not None
            assert isinstance(interview.id, uuid.UUID)
            
            # Verify the ID was generated by the database
            interview_id = interview.id
            
            # Now create a notification using the interview ID
            notification = Notification(
                user_id=user.id,
                title="Test Notification",
                content="Test notification content",
                notification_type="interview_scheduled",
                entity_type="interview",
                entity_id=interview_id
            )
            session.add(notification)
            await session.flush()
            
            # Verify notification has the correct entity_id
            assert notification.entity_id == interview_id
            
            await session.commit()

    async def test_interview_id_generated_before_notification(self):
        """Test that interview.id is generated before notification uses it."""
        from app.database.session import async_session_factory
        from app.models import Interview, Application, Job, User, Company, CandidateProfile, RecruiterProfile, Notification
        from app.domain.enums import InterviewStatus, InterviewType, ApplicationStatus, UserRole, CompanySize
        import uuid
        from datetime import datetime, timedelta, timezone
        
        async with async_session_factory() as session:
            # Create test data
            company = Company(
                id=uuid.uuid4(),
                name="Test Company",
                slug="test-company",
                tax_code="123456789",
                size=CompanySize.STARTUP
            )
            session.add(company)
            
            user = User(
                id=uuid.uuid4(),
                email="test@example.com",
                password_hash="hash",
                role="recruiter",
                is_active=True
            )
            session.add(user)
            
            recruiter_profile = RecruiterProfile(
                id=uuid.uuid4(),
                user_id=user.id,
                company_id=company.id,
                full_name="Test Recruiter"
            )
            session.add(recruiter_profile)
            
            job = Job(
                id=uuid.uuid4(),
                company_id=company.id,
                title="Test Job",
                description="Test job",
                status="published",
                job_type="full_time",
                workplace_type="remote",
                location="Remote"
            )
            session.add(job)
            
            candidate_user = User(
                id=uuid.uuid4(),
                email="candidate@example.com",
                password_hash="hash",
                role="candidate",
                is_active=True
            )
            session.add(candidate_user)
            
            candidate_profile = CandidateProfile(
                id=uuid.uuid4(),
                user_id=candidate_user.id,
                full_name="Test Candidate"
            )
            session.add(candidate_profile)
            
            application = Application(
                id=uuid.uuid4(),
                candidate_id=candidate_profile.id,
                job_id=job.id,
                status=ApplicationStatus.APPLIED
            )
            session.add(application)
            
            await session.flush()
            
            # Create interview
            interview = Interview(
                application_id=application.id,
                scheduled_at=datetime.now(timezone.utc) + timedelta(days=1),
                duration_minutes=60,
                interview_type=InterviewType.TECHNICAL,
                meeting_url="https://meet.example.com",
                location="Office",
                notes="Test interview",
                status=InterviewStatus.SCHEDULED
            )
            
            # Before flush, id should be None
            assert interview.id is None
            
            session.add(interview)
            await session.flush()
            
            # After flush, id should be generated
            assert interview.id is not None
            assert isinstance(interview.id, uuid.UUID)
            
            # Verify the ID was generated by the database
            interview_id = interview.id
            
            # Now create a notification using the interview ID
            notification = Notification(
                user_id=application.candidate_id,  # candidate user id
                title="Test Notification",
                content="Test notification content",
                notification_type="interview_scheduled",
                entity_type="interview",
                entity_id=interview_id
            )
            session.add(notification)
            await session.flush()
            
            # Verify notification has the correct entity_id
            assert notification.entity_id == interview_id
            
            await session.commit()